name: afqi0.7
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adwaita-icon-theme=48.1
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.22.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.1.0
  - babel=2.17.0
  - bambi=0.15.0
  - beautifulsoup4=4.13.3
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.1.0
  - cairo=1.18.4
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cloudpickle=3.1.1
  - comm=0.2.2
  - cons=0.4.7
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - epoxy=1.5.10
  - etuples=0.3.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - formulae=0.5.4
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc=14.2.0
  - gcc_impl_linux-64=14.2.0
  - gcc_linux-64=14.2.0
  - gdk-pixbuf=2.42.12
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx=14.2.0
  - gxx_impl_linux-64=14.2.0
  - gxx_linux-64=14.2.0
  - h11=0.14.0
  - h2=4.2.0
  - h5netcdf=1.6.3
  - harfbuzz=11.0.0
  - hdf5=1.14.3
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.50
  - librsvg=2.58.4
  - libsanitizer=14.2.0
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxml2=2.13.7
  - libzlib=1.3.1
  - logical-unification=0.4.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minikanren=1.0.5
  - mistune=3.1.1
  - mkl=2022.1.0
  - mkl-service=2.4.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - openblas=0.3.29
  - openjpeg=2.5.3
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pymc=5.24.0
  - pymc-base=5.24.0
  - pysocks=1.7.1
  - pytensor=2.31.7
  - pytensor-base=2.31.7
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.21
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rpds-py=0.22.3
  - send2trash=1.8.3
  - setuptools=75.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xarray=2025.7.1
  - xarray-einstats=0.9.1
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - afqinsight==0.7
      - contourpy==1.3.1
      - copt==0.9.1
      - deepdiff==8.2.0
      - dipy==1.9.0
      - fonttools==4.55.8
      - groupyr==0.3.4
      - h5py==3.12.1
      - joblib==1.4.2
      - matplotlib==3.10.0
      - nibabel==5.3.2
      - numpy==2.0.0
      - orderly-set==5.3.0
      - pandas==2.2.3
      - pillow==11.1.0
      - pyaml==25.1.0
      - pyparsing==3.2.1
      - scikit-learn==1.5.2
      - scikit-optimize==0.9.0
      - scipy==1.13.1
      - seaborn==0.13.0
      - setuptools-scm==8.1.0
      - sklearn-pandas==2.2.0
      - statsmodels==0.14.4
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - trx-python==0.3
      - tzdata==2025.1
